# Generated by Django 3.1.5 on 2021-07-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0002_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.TextField(default='str(randint(10000000,99999999))'),
        ),
    ]
