# Generated by Django 3.1.5 on 2021-07-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0003_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.TextField(default='43067056'),
        ),
    ]
