# Generated by Django 3.1.5 on 2021-07-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0004_auto_20210703_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.TextField(verbose_name='93425514'),
        ),
    ]
