# Generated by Django 3.1.5 on 2021-07-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0005_auto_20210703_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default=31077972, max_length=8),
        ),
    ]
