# Generated by Django 3.1.5 on 2021-07-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0006_auto_20210703_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='customer_phone',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='brand',
            new_name='item_brand',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='item_description',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='type',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='picture',
            new_name='item_picture',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='item_price',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='summary',
            new_name='item_summary',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='weight',
            new_name='item_weight',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='order_customer_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='items',
            new_name='order_items',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='item',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordered_item',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_address1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_address2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_payment_method',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='order',
            name='order_tracking_code',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderquantity',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
