# Generated by Django 3.1.5 on 2021-07-05 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0007_auto_20210704_1725'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
