# Generated by Django 3.1.5 on 2021-07-05 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0008_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_tracking_code', models.CharField(max_length=15, null=True)),
                ('order_first_name', models.CharField(max_length=50, null=True)),
                ('order_last_name', models.CharField(max_length=50, null=True)),
                ('order_email', models.EmailField(max_length=254, null=True)),
                ('order_phone', models.CharField(max_length=50, null=True)),
                ('order_address', models.TextField(null=True)),
                ('order_payment_method', models.CharField(max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('order_total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('order_customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buy.customer')),
                ('order_items', models.ManyToManyField(to='buy.Item')),
            ],
        ),
    ]
