# Generated by Django 3.1.5 on 2021-07-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0009_myorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myorder',
            name='order_items',
        ),
        migrations.AlterField(
            model_name='item',
            name='item_picture',
            field=models.ImageField(default='images/0177.jpg', upload_to='images/'),
        ),
    ]
